// src/components/Footer.tsx
export default function Footer() {
  return (
    <>
      <footer className="mt-32 text-xs text-center text-muted-foreground">
        &copy; {new Date().getFullYear()} David Pescariu - View source{" "}
        <a
          href="https://github.com/davidp-ro/portfolio"
          target="_blank"
          rel="noopener noreferrer"
          className="hover:underline"
        >
          here
        </a>
        .
      </footer>
      <div className="h-8" />
    </>
  );
}

// src/lib/components/footer.svelte
<footer class="mt-80 text-center text-sm">
  <p class="text-gray-400">
    Built with Svelte & Tailwind - <a
      href="https://github.com/davidp-ro/portfolio"
      target="_blank"
      rel="noopener noreferer"
    >
      View Repo
    </a>
  </p>
  <p class="text-gray-500">
    &copy; David Pescariu {new Date().getFullYear()}
  </p>
</footer>
<div class="h-10" aria-hidden="true" />
